#!/bin/sh

# Exit on any error
set -euo pipefail

if [[ -n "${SKIP_GIT_HOOKS-}" ]]; then exit 0; fi

npm run prettier
npm run lint
npm run tsc
npm run build
# dont run test on pre-push to save time, ci will run anyway.
# npm test

# todo: knip
